### ISSUE TITLE
3XX redirect in sitemap

### ISSUE THREAD

**Issue by roy-shiloh** [Vinyl-Depository/landing-page#202]
Issue details

**https://vinyldepository.com/** 

URLs included in sitemap file that redirect.
Sitemap must list all the pages you want search engines to crawl and index.
Redirecting URLs in sitemaps can result in indexability issues on your website.

**How to fix**
Replace the redirecting URLs in the sitemaps with the destination URL. If the destination URL is already listed, simply remove the URL that redirects to it from the sitemap file.

**DOD**
Attach a new sitemap.xml url please 💯 :^)

**Comment by tal-rofe** [comment]
current sitemap
![image](https://user-images.githubusercontent.com/100444463/162675599-8ad36af1-97f7-495e-8a24-9d90a100ce33.png)


Should the URL be replaces with <?>?

**Comment by roy-shiloh** [comment]
www...

**Comment by tal-rofe** [comment]
@roy-shiloh 
Done
